data = [
// math
{img: "math/divide.svg", name:"divide"},
{img: "math/equals.svg", name:"equals"},
{img: "math/minus.svg", name:"minus"},
{img: "math/n0.svg", name:"0"},
{img: "math/n1.svg", name:"1\n(+*) only, sole\n(+#) the first, number one\n(+adverb) only, solely, just"},
{img: "math/n2.svg", name:"2"},
{img: "math/n3.svg", name:"3"},
{img: "math/n4.svg", name:"4"},
{img: "math/n5.svg", name:"5"},
{img: "math/n6.svg", name:"6"},
{img: "math/n7.svg", name:"7"},
{img: "math/n8.svg", name:"8"},
{img: "math/n9.svg", name:"9"},
{img: "math/ordinal number.svg", name:"ordinal number suffix\n(1+) first\n(2+) second\n(finish+) last"},
{img: "math/plus.svg", name:"plus"},
{img: "math/times, multiply.svg", name:"times"},
// arrows
{img: "arrows/across, through.svg", name:"across\n(+go) to cross, to traverse"},
{img: "arrows/after, behind.svg", name:"after\n(+go) to follow"},
{img: "arrows/again, for.svg", name:"again\n(thing+)a time, repetition\n(+do) to repeat, to redo"},
{img: "arrows/against.svg", name:"against\ninstead of\n(+stand)to oppose\n(+stand+thing) obstacle, difficulty"},
{img: "arrows/along.svg", name:"along\n(+go) to go by, to follow through"},
{img: "arrows/apart.svg", name:"apart\n(+go) to go apart"},
{img: "arrows/around.svg", name:"around\n (+go) to circumvent, to go around, to avoid\n(around+go+no) inevitable, unavoidable"},
{img: "arrows/back, backward.svg", name:"back, backwards\n (+go) to return\n (+side) back"},
{img: "arrows/before.svg", name:"before\n (+go) to precede \n(+think) to plan, to intent\n(+think+thing) planning, plan \n(+think+piece) reason, intention, meaning"},
{img: "arrows/between, among.svg", name:"between"},
{img: "arrows/down.svg", name:"down\n (+go) to descend"},
{img: "arrows/forth, forward.svg", name:"forth, forward\n(+go) to progress, to proceed, to continue"},
{img: "arrows/from, of, because.svg", name:"from\n because of \n (go+) to depart \n (+thing) cause"},
{img: "arrows/in, into.svg", name:"in \n (+go) to enter, to go in \n (+put) to enter, to insert, to input\n(in+place) instead"},
{img: "arrows/left.svg", name:"left"},
{img: "arrows/of.svg", name:"of \n(+thing) property"},
{img: "arrows/off.svg", name:"off \n (+go) to step off"},
{img: "arrows/on, upon.svg", name:"on\n (+go) to step on"},
{img: "arrows/out, outside.svg", name:"out\n (+go) to exit"},
{img: "arrows/over, above.svg", name:"over\n(+go) to overcome"},
{img: "arrows/right.svg", name:"right"},
{img: "arrows/to, at, for.svg", name:"to, towards, at\n(+go) to approach, to come"},
{img: "arrows/together.svg", name:"together\n(+go) to meet together, to gather\n(+go+thing) meeting, gathering"},
{img: "arrows/under, below.svg", name:"under, below"},
{img: "arrows/up.svg", name:"up\n(+go) to ascend"},
// evaluation
{img: "evaluation/bad.svg", name:"bad\n(+thing) badness, harm\n(+say) to curse\n(+do) to harm"},
{img: "evaluation/beautiful.svg", name:"beautiful, pretty\n(+thing) beauty\n(no+) ugly"},
{img: "evaluation/different, other.svg", name:"different\n(+thing) difference\n(+piece) distinction\n(+causative) to change, to alter\n(+causative+thing) changing, change"},
{img: "evaluation/false, no.svg", name:"false\n no, wrong \n(+thing) falsehood\n(+say) to lie"},
{img: "evaluation/good.svg", name:"good\n(+thing) goodness\n (tool+) useful\n (+say) to bless \n(+do) to benefit, to do good"},
{img: "evaluation/perfect.svg", name:"perfect \n (+causative) to perfect"},
{img: "evaluation/same, equal.svg", name:"same\n (+thing) sameness, equality \n(+causative) equalize"},
{img: "evaluation/similar, alike.svg", name:"similar\n (+thing) similarity, likeness"},
{img: "evaluation/true, yes.svg", name:"true\n yes, right \n(+thing) truth \n (+causative) to actualize, to realize \n (+adverb) really, trully"},
// adjectives
{img: "adjectives/big.svg", name:"big, great\n(+causative) to magnify, to enlarge"},
{img: "adjectives/bright.svg", name:"bright\n (+causative) to brighten"},
{img: "adjectives/closed.svg", name:"closed\n(+causative) to close"},
{img: "adjectives/cold.svg", name:"cold\n(+causative) to cool"},
{img: "adjectives/dark.svg", name:"dark"},
{img: "adjectives/dense.svg", name:"dense, compact, tight\n(+causative) to tighten"},
{img: "adjectives/dim.svg", name:"dim"},
{img: "adjectives/dry.svg", name:"dry\n(+causative) to dry"},
{img: "adjectives/empty.svg", name:"empty\n(+thing) emptiness, vacuum\n(+causative) to empty"},
{img: "adjectives/fast.svg", name:"fast, quick\n(+thing) speed, velocity\n(+causative) to accelerate\n(+causative+thing) acceleration"},
{img: "adjectives/femal.svg", name:"female\n(+causative) feminize"},
{img: "adjectives/fragile.svg", name:"fragile\n(+thing) fragility"},
{img: "adjectives/free, loose.svg", name:"free, loose\n(+thing) freedom, liberty\n(+causative) to free, to liberate, to set loose"},
{img: "adjectives/frequent, prevalent.svg", name:"frequent\n(+thing) frequency\n(+adverb) frequently, often"},
{img: "adjectives/fresh.svg", name:"fresh\n(+thing) freshness"},
{img: "adjectives/full.svg", name:"full\n (+thing) fullness\n(+causative) to fill"},
{img: "adjectives/gas.svg", name:"gas\n(liquid+) vapor"},
{img: "adjectives/heavy.svg", name:"heavy\n(+thing) weight, mass"},
{img: "adjectives/hot.svg", name:"hot\n(+thing) hotness, temperature \n(+causative) to heat"},
{img: "adjectives/light.svg", name:"light, lightweight"},
{img: "adjectives/liquid.svg", name:"liquid\n(+gas) vapor\n(+do) to flow"},
{img: "adjectives/loud.svg", name:"loud\n(+thing) loudness"},
{img: "adjectives/male.svg", name:"male\n(+causative) to masculinize"},
{img: "adjectives/mighty, powerful.svg", name:"mighty, powerful\n(+thing) might, power, ability\n(+causative) to strengthen, to empower\n(no+) powerless, weak"},
{img: "adjectives/new.svg", name:"new\n(+thing) novelty"},
{img: "adjectives/old.svg", name:"old\n(+thing) oldness, age"},
{img: "adjectives/open.svg", name:"open\n(+causative) to open"},
{img: "adjectives/quiet.svg", name:"quiet"},
{img: "adjectives/rare, infrequent.svg", name:"rare"},
{img: "adjectives/silent.svg", name:"silent\n(+thing) silence\n(+causative) to mute, to silence"},
{img: "adjectives/slow.svg", name:"slow\n(+causative) to slow down"},
{img: "adjectives/small.svg", name:"small\n(+causative) to diminish"},
{img: "adjectives/soft.svg", name:"soft\n(+thing) softness\n(+causative) to soften"},
{img: "adjectives/solid, hard.svg", name:"solid, hard\n(+thing) solidity, hardness\n(+causative) to solidify"},
{img: "adjectives/sticky, viscous.svg", name:"sticky, viscous\n(+do) to stick"},
{img: "adjectives/strong.svg", name:"strong, intense\n(+thing) force, intensity\n(+causative) to strengthen, to intensify"},
{img: "adjectives/warm.svg", name:"warm\n(+causative) to warm up"},
{img: "adjectives/weak.svg", name:"weak\n(+thing) weakness\n(+causative) to weaken"},
{img: "adjectives/wet.svg", name:"wet\n(+thing) wetness, humidity"},
{img: "adjectives/young.svg", name:"young\n (+thing) youth\n(+people) the youth"},
// faces
{img: "faces/afraid.svg", name:"afraid\n(+thing) fear\n(+do) to fear\n(+causative) to scare\n(big+) in terror, in panic\n(no+) fearless, brave"},
{img: "faces/alive.svg", name:"alive\n(alive+do) to live\n(alive+thing) life, living\n(through+alive) survived, survivour\n(through+alive+do) to survive\n(through+alive+thing) survival\n(alive+causative) to animate to bring to life\n(alive+able) viable\n(alive+know+thing) biology"},
{img: "faces/amazed, fascinated.svg", name:"amazed, fascinated\n(+thing) wonder, marvel, fascination\n(+causative) to amaze, to fascinate"},
{img: "faces/amused, excited.svg", name:"amused\n(+thing) fun, entertainment\n(+do) to have fun\n(+causative) to amuse, to entertain"},
{img: "faces/angry.svg", name:"angry\n(+thing) anger, rage\n(+do) to rage\n(+causative) to enrage, to infuriate, to make mad"},
{img: "faces/ashamed, embarrased.svg", name:"ashamed, embarrased\n(+thing) shame, embarrasment\n(+causative) to ashame, to embarras"},
{img: "faces/bored.svg", name:"bored, unexcited\n(+thing) boredom\n(+do) to feel boredom\n(+causative)to bore"},
{img: "faces/calm.svg", name:"calm, peaceful\n(+thing) calmness, peace\n(+do) to rest\n(+causative) to calm down, to pacify\n(no+) excited, disturbed\n(+no) trubulence, unrest, excitement"},
{img: "faces/confused.svg", name:"confused\n(+causative) to confuse\n(+causative+active pt.) confusing"},
{img: "faces/cool, confident.svg", name:"cool, confident\n(+thing) confidence"},
{img: "faces/dead.svg", name:"dead\n(+thing) death\n (+causative) to kill, to put to death\n(+able) mortal"},
{img: "faces/delirious.svg", name:"crazy, delirious\n(+thing) madness, delirium"},
{img: "faces/derivate, adjective.svg", name:"adjective (frequently used derivative suffix)"},
{img: "faces/disgusted.svg", name:"disgusted\n(+causative) to disgust"},
{img: "faces/doubt.svg", name:"in doubt\n(+do) to doubt\n (+do) to doubt, to question\n(no+) unskeptical, credule"},
{img: "faces/enamorado.svg", name:"in love"},
{img: "faces/evil, malevolent.svg", name:"evil\n(evil+thing) evil, malice, villianry\n(evil+piece) sin, wrongdoing"},
{img: "faces/greedy.svg", name:"greedy\n(+thing) greed"},
{img: "faces/happy.svg", name:"happy\n(+thing) happiness\n(+do) to rejoice, to like"},
{img: "faces/healthy.svg", name:"healthy\n(+thing) health, vigour\n(+causative) to heal"},
{img: "faces/hungry, thirsty.svg", name:"hungry\n(+thing) hunger\n(big+) starving"},
{img: "faces/hurt, in-pain.svg", name:"in pain, hurt\n(+thing) pain\n(no+) unhurt"},
{img: "faces/rich.svg", name:"rich\n(+thing) wealth"},
{img: "faces/righteous.svg", name:"good, righteous\n(+thing) morality, righteousness"},
{img: "faces/sad.svg", name:"sad\n(+thing) sadness\n(+do) to feel down\n(big+) depressed"},
{img: "faces/sick.svg", name:"sick\n(+thing) sickness, disease"},
{img: "faces/silly.svg", name:"silly, stupid\n(+thing) silliness"},
{img: "faces/smart.svg", name:"smart, clever\n(+thing) smartness, intelligence"},
{img: "faces/surprised.svg", name:"surprised\n(+thing) wonder, surprise\n(+causative) to surprise"},
{img: "faces/tired.svg", name:"tired\n(+thing) fatigue\n(+causative) to exhaust\n(big+) exhausted"},
// abstract
{img: "abstract/be, exist.svg", name:"be, exist\n(+thing) being\n(+causative) to create"},
{img: "abstract/body.svg", name:"body\n(+adjective) corporal"},
{img: "abstract/border, boundary.svg", name:"border, boundary"},
{img: "abstract/danger.svg", name:"danger\n(+rich) risky, dangerous\n(+adjective) risk-related"},
{img: "abstract/direction.svg", name:"direction\n(+adjective) directional"},
{img: "abstract/game.svg", name:"game\n(+do) to play"},
{img: "abstract/half.svg", name:"half\n(+causative) to halve"},
{img: "abstract/justice, right.svg", name:"justice\n(+do) to judge \n(+adjective) just, fair\n(+adverb) justly, fairly"},
{img: "abstract/layer.svg", name:"layer\n(+adjective) layered, complex\n(+adjective+thing) complexity"},
{img: "abstract/luck.svg", name:"luck\n(+adjective) lucky, fortunate\n(+no) unlucky, unfortunate"},
{img: "abstract/magic.svg", name:"magic\n(+adjective) magical\n(+do) to enchant, to bewitch"},
{img: "abstract/mind.svg", name:"mind\n(+adjective) meantal"},
{img: "abstract/music.svg", name:"music\n(+adjective) musical\n(begin+music) overture, (musical) intro"},
{img: "abstract/name.svg", name:"name\n(+adjective) nominal"},
{img: "abstract/number.svg", name:"number\n(+adjective) numeral\n(+do) to count, to enumerate"},
{img: "abstract/peace.svg", name:"peace\n(+adjective) peaceful, peace-related\n(+do) to tolerate"},
{img: "abstract/piece, part.svg", name:"piece, part\n(frequently used suffix)"},
{img: "abstract/random.svg", name:"random\n(+thing) randomness, chance, chaos"},
{img: "abstract/relationships.svg", name:"relationships"},
{img: "abstract/section, part.svg", name:"section"},
{img: "abstract/side.svg", name:"side"},
{img: "abstract/thing.svg", name:"thing\n(frequently used suffix to create abstract nouns)"},
{img: "abstract/total, whole.svg", name:"total, whole\ncompletely, totally\n(no+) incomplete"},
{img: "abstract/wave.svg", name:"wave"},
{img: "abstract/way, method.svg", name:"way, method, manner"},
// materials
{img: "materials/atom.svg", name:"atom"},
{img: "materials/blood.svg", name:"blood"},
{img: "materials/bread.svg", name:"bread"},
{img: "materials/chain.svg", name:"chain"},
{img: "materials/clay.svg", name:"clay"},
{img: "materials/coal.svg", name:"coal"},
{img: "materials/drop.svg", name:"drop"},
{img: "materials/electricity.svg", name:"electricity"},
{img: "materials/fire.svg", name:"fire\n(fire+piece) flame\n(fire+adjective) fiery, igneous"},
{img: "materials/glass.svg", name:"glass"},
{img: "materials/gold.svg", name:"gold"},
{img: "materials/ice.svg", name:"ice"},
{img: "materials/iron.svg", name:"iron"},
{img: "materials/matter.svg", name:"matter"},
{img: "materials/meat.svg", name:"meat"},
{img: "materials/paper.svg", name:"paper"},
{img: "materials/poop.svg", name:"poop"},
{img: "materials/rope.svg", name:"rope"},
{img: "materials/silver.svg", name:"silver"},
{img: "materials/soil, dirt.svg", name:"soil"},
{img: "materials/steel.svg", name:"steel"},
{img: "materials/stone, rock.svg", name:"stone"},
{img: "materials/water.svg", name:"water"},
// shapes
{img: "shapes/angle, corner.svg", name:"angle"},
{img: "shapes/arc.svg", name:"arc"},
{img: "shapes/bottom.svg", name:"bottom"},
{img: "shapes/circle.svg", name:"circle"},
{img: "shapes/close.svg", name:"close"},
{img: "shapes/cube.svg", name:"cube"},
{img: "shapes/cyllinder.svg", name:"cyllinder"},
{img: "shapes/direct, stright.svg", name:"direct"},
{img: "shapes/dot, point.svg", name:"dot"},
{img: "shapes/far.svg", name:"far\n(+thing) distance, remoteness\n(between+/+thing) interval"},
{img: "shapes/grid.svg", name:"grid"},
{img: "shapes/indirect.svg", name:"indirect\n(+causative) to curve and twist"},
{img: "shapes/line.svg", name:"line"},
{img: "shapes/long.svg", name:"long\n(+thing) length\n(+adverb) long (time)"},
{img: "shapes/narrow (thin).svg", name:"narrow, thin\n(+causative) to narrow down"},
{img: "shapes/next.svg", name:"next\n(+do) to continue"},
{img: "shapes/oval.svg", name:"oval"},
{img: "shapes/plane, flat.svg", name:"plane"},
{img: "shapes/previous.svg", name:"previous"},
{img: "shapes/ray.svg", name:"ray"},
{img: "shapes/rhombus.svg", name:"rhombus"},
{img: "shapes/round.svg", name:"round"},
{img: "shapes/shape.svg", name:"shape\n(shape+causative) to shape\n(shape+know+thing) geometry"},
{img: "shapes/sharp.svg", name:"sharp, acute"},
{img: "shapes/short(low).svg", name:"short (low, non-long)"},
{img: "shapes/short.svg", name:"short"},
{img: "shapes/space.svg", name:"space"},
{img: "shapes/sphere, ball.svg", name:"sphere"},
{img: "shapes/square.svg", name:"square"},
{img: "shapes/tall.svg", name:"tall"},
{img: "shapes/thick (wide).svg", name:"thick, wide, broad"},
{img: "shapes/top.svg", name:"top"},
// color
{img: "color/black.svg", name:"black"},
{img: "color/blue.svg", name:"blue"},
{img: "color/brown.svg", name:"brown"},
{img: "color/clear, transparent.svg", name:"clear, transparent"},
{img: "color/color.svg", name:"color"},
{img: "color/dirty, tainted.svg", name:"dirty, stained"},
{img: "color/green.svg", name:"green"},
{img: "color/grey.svg", name:"grey"},
{img: "color/pink.svg", name:"pink"},
{img: "color/red.svg", name:"red"},
{img: "color/spotted, dotted.svg", name:"spotted, dotted"},
{img: "color/striped.svg", name:"striped"},
{img: "color/white.svg", name:"white"},
{img: "color/yellow.svg", name:"yellow"},
// tools
{img: "tools/axe.svg", name:"axe"},
{img: "tools/broom.svg", name:"broom"},
{img: "tools/brush.svg", name:"brush"},
{img: "tools/fork.svg", name:"fork"},
{img: "tools/hammer.svg", name:"hammer"},
{img: "tools/knife.svg", name:"knife"},
{img: "tools/pickaxe.svg", name:"pickaxe"},
{img: "tools/rake.svg", name:"rake"},
{img: "tools/ruler.svg", name:"ruler"},
{img: "tools/scythe.svg", name:"scythe"},
{img: "tools/spade, shovel.svg", name:"spade"},
{img: "tools/spoon.svg", name:"spoon"},
{img: "tools/tool.svg", name:"tool"},
{img: "tools/torch.svg", name:"torch"},
{img: "tools/wand.svg", name:"wand"},
{img: "tools/wrench.svg", name:"wrench"},
// items
{img: "items/arms.svg", name:"arms\n(+house) arsenal"},
{img: "items/arrow.svg", name:"arrow"},
{img: "items/battery.svg", name:"battery"},
{img: "items/boat.svg", name:"boat"},
{img: "items/book.svg", name:"book"},
{img: "items/bottle.svg", name:"bottle"},
{img: "items/bow.svg", name:"bow"},
{img: "items/brick.svg", name:"brick"},
{img: "items/card.svg", name:"card\n (+do) to play cards"},
{img: "items/cart, car.svg", name:"cart"},
{img: "items/clocks.svg", name:"clocks"},
{img: "items/coin.svg", name:"coin"},
{img: "items/compass.svg", name:"compass\n(+do) to orient, to navigate around"},
{img: "items/dice.svg", name:"dice"},
{img: "items/floppy.svg", name:"floppy"},
{img: "items/globe.svg", name:"globe"},
{img: "items/jigsaw, puzzle.svg", name:"jigsaw"},
{img: "items/lightbulb.svg", name:"lightbulb"},
{img: "items/map.svg", name:"map"},
{img: "items/money.svg", name:"money"},
{img: "items/painting.svg", name:"painting"},
{img: "items/pedestal.svg", name:"pedestal"},
{img: "items/poison, venom, toxin.svg", name:"poison"},
{img: "items/scales.svg", name:"scales"},
{img: "items/shield.svg", name:"shield"},
{img: "items/spear.svg", name:"spear"},
{img: "items/steering-wheel.svg", name:"steering wheel"},
{img: "items/stopwatch.svg", name:"stopwatch"},
{img: "items/sword.svg", name:"sword"},
{img: "items/target.svg", name:"target"},
{img: "items/tea.svg", name:"tea\n(+do) to have tea"},
{img: "items/thread.svg", name:"thread"},
// place
{img: "place/castle.svg", name:"castle"},
{img: "place/ceiling.svg", name:"ceiling"},
{img: "place/channel.svg", name:"channel"},
{img: "place/city.svg", name:"city\n(+adjective) urban, city-related"},
{img: "place/desert.svg", name:"desert"},
{img: "place/door.svg", name:"door"},
{img: "place/east.svg", name:"east\n(+adjective) oriental"},
{img: "place/field.svg", name:"field"},
{img: "place/floor.svg", name:"floor"},
{img: "place/forest.svg", name:"forest"},
{img: "place/foundation, base.svg", name:"foundation"},
{img: "place/gates.svg", name:"gates"},
{img: "place/home, house.svg", name:"home, house\n(frequently used as a suffix for a specialized place)"},
{img: "place/island.svg", name:"island"},
{img: "place/land.svg", name:"land"},
{img: "place/mountain.svg", name:"mountain\n(+rich) mountainous"},
{img: "place/north.svg", name:"north\n(+adjective) northern, septentrional"},
{img: "place/place.svg", name:"place\n(+adjective) local"},
{img: "place/river, stream.svg", name:"river"},
{img: "place/road.svg", name:"road"},
{img: "place/roof.svg", name:"roof"},
{img: "place/room.svg", name:"room"},
{img: "place/sea, ocean.svg", name:"sea"},
{img: "place/south.svg", name:"south"},
{img: "place/stair.svg", name:"stair"},
{img: "place/store.svg", name:"store"},
{img: "place/temple.svg", name:"temple"},
{img: "place/tile.svg", name:"tile"},
{img: "place/tower.svg", name:"tower"},
{img: "place/valley.svg", name:"valley"},
{img: "place/village.svg", name:"village\n(+adjective) rural"},
{img: "place/wall.svg", name:"wall"},
{img: "place/west.svg", name:"west"},
{img: "place/window.svg", name:"window"},
{img: "place/woods.svg", name:"woods, grove"},
{img: "place/yard.svg", name:"yard"},
// sky
{img: "sky/cloud.svg", name:"cloud"},
{img: "sky/moon, crescent.svg", name:"moon\n(+adjective) lunar"},
{img: "sky/planet, world.svg", name:"planet, world\n(+adjective) planetary\n(all+) universe"},
{img: "sky/rain.svg", name:"rain\n(+do) to rain"},
{img: "sky/sky, heavens.svg", name:"sky\n(+adjective) celestial, sky-related"},
{img: "sky/snow.svg", name:"snow\n(+do) to snow"},
{img: "sky/star.svg", name:"star"},
{img: "sky/sun.svg", name:"sun\n(+adjective) solar"},
{img: "sky/wind.svg", name:"wind\n(+rich) windy\n(big+) storm"},
// time
{img: "time/autumn.svg", name:"autumn"},
{img: "time/date.svg", name:"date"},
{img: "time/day.svg", name:"day\n(+adjective) diurnal, day-related"},
{img: "time/daynight.svg", name:"daynight"},
{img: "time/eternity.svg", name:"eternity\n(+adjective) eternal"},
{img: "time/evening.svg", name:"evening"},
{img: "time/hour.svg", name:"hour"},
{img: "time/minute.svg", name:"minute"},
{img: "time/month.svg", name:"month"},
{img: "time/morning.svg", name:"morning"},
{img: "time/night.svg", name:"night"},
{img: "time/secund.svg", name:"secund"},
{img: "time/spring.svg", name:"spring"},
{img: "time/summer.svg", name:"summer"},
{img: "time/sunrise.svg", name:"sunrise"},
{img: "time/sunset.svg", name:"sunset"},
{img: "time/time.svg", name:"time\n(before+) early\n(after+) late, lately\n(to+) ready\n(to+/+causative) to prepare, to get ready"},
{img: "time/week.svg", name:"week"},
{img: "time/winter.svg", name:"winter"},
{img: "time/year.svg", name:"year"},
// people
{img: "people/baby.svg", name:"baby"},
{img: "people/boy.svg", name:"boy"},
{img: "people/brother.svg", name:"brother"},
{img: "people/child.svg", name:"child, offspring, descendant"},
{img: "people/cook.svg", name:"cook\n(+do) to cook, to make food\n(+house) restoraunt\n(+room) kitchen"},
{img: "people/crowd, mob.svg", name:"crowd, mob"},
{img: "people/dad, father.svg", name:"dad, father"},
{img: "people/demon.svg", name:"demon"},
{img: "people/doctor.svg", name:"doctor\n(+house) hospital\n(+do) to cure, to medicate"},
{img: "people/elder.svg", name:"elder"},
{img: "people/elf.svg", name:"elf"},
{img: "people/family.svg", name:"family\n(family+person) relative\n(family+crowd) clan, (ethnic) tribe"},
{img: "people/farmer.svg", name:"farmer\n(+do) to farm, to cultivate"},
{img: "people/friend.svg", name:"friend\n(adjective+) friendly\n(love+) lover\n(no+) enemy\n(no+/+adjective) enemious, hostile"},
{img: "people/girl.svg", name:"girl"},
{img: "people/gnome, dwarf.svg", name:"gnome"},
{img: "people/god.svg", name:"god"},
{img: "people/jaintor.svg", name:"jaintor\n(+do) to tidy up"},
{img: "people/kid.svg", name:"kid"},
{img: "people/man.svg", name:"man, husband"},
{img: "people/mom, mother.svg", name:"mom, mother"},
{img: "people/monarch.svg", name:"monarch\n(+thing) monarchy\n(+adjective) royal"},
{img: "people/orc, ogre.svg", name:"orc"},
{img: "people/parent.svg", name:"parent\n(+father) grandfather\n(+mother) grandmother\n(+brother) uncle\n(+sister) aunt"},
{img: "people/people.svg", name:"people\n(people+know+thing) sociology"},
{img: "people/goblin.svg", name:"goblin"},
{img: "people/person.svg", name:"person"},
{img: "people/prisoner, inmate.svg", name:"prisoner\n(+house) prison, jail"},
{img: "people/sibling.svg", name:"sibling"},
{img: "people/sister.svg", name:"sister"},
{img: "people/spirit, ghost.svg", name:"spirit\n(+adjective) spiritual, ghostly\n(+do) to haunt"},
{img: "people/student.svg", name:"student\n(+do) to study\n(big+/+house) college\n(small+/+house) school"},
{img: "people/warrior.svg", name:"warrior"},
{img: "people/woman.svg", name:"woman"},
{img: "people/worker.svg", name:"worker"},
// animals
{img: "animals/beast.svg", name:"mammal, beast\n(adjective) bestial"},
{img: "animals/bee.svg", name:"bee"},
{img: "animals/bird.svg", name:"bird"},
{img: "animals/bug.svg", name:"bug"},
{img: "animals/cat.svg", name:"cat"},
{img: "animals/chicken.svg", name:"chicken"},
{img: "animals/chirp.svg", name:"chirp"},
{img: "animals/cow.svg", name:"cow"},
{img: "animals/deer.svg", name:"deer"},
{img: "animals/dog.svg", name:"dog"},
{img: "animals/feather.svg", name:"feather"},
{img: "animals/fish.svg", name:"fish"},
{img: "animals/flamingo.svg", name:"flamingo"},
{img: "animals/frog, toad.svg", name:"frog"},
{img: "animals/grasshopper.svg", name:"grasshopper"},
{img: "animals/hare, rabbit.svg", name:"hare"},
{img: "animals/horse.svg", name:"horse"},
{img: "animals/insect.svg", name:"insect"},
{img: "animals/rat, mouse.svg", name:"rat"},
{img: "animals/raven.svg", name:"raven"},
{img: "animals/shellfish.svg", name:"shellfish"},
{img: "animals/snake, viper, serpent.svg", name:"snake"},
{img: "animals/wolf.svg", name:"wolf"},
// body parts
{img: "body/arm.svg", name:"arm"},
{img: "body/brain.svg", name:"brain"},
{img: "body/ear.svg", name:"ear"},
{img: "body/elbow.svg", name:"elbow"},
{img: "body/eye-brow.svg", name:"eye-brow"},
{img: "body/eye-pupil.svg", name:"eye-pupil"},
{img: "body/eye.svg", name:"eye"},
//{img: "body/eyelash-1.svg", name:"eyelid"},
{img: "body/eyelash.svg", name:"eyelash"},
{img: "body/eyelid.svg", name:"eyelid"},
{img: "body/face.svg", name:"face"},
{img: "body/finger.svg", name:"finger"},
{img: "body/fist.svg", name:"fist"},
{img: "body/foot.svg", name:"foot"},
{img: "body/hair.svg", name:"hair"},
{img: "body/hand.svg", name:"hand"},
{img: "body/head.svg", name:"head"},
{img: "body/heart.svg", name:"heart"},
{img: "body/heel.svg", name:"heel"},
{img: "body/kidney.svg", name:"kidney"},
{img: "body/knee.svg", name:"knee"},
{img: "body/leg.svg", name:"leg"},
{img: "body/lungs.svg", name:"lungs"},
{img: "body/mouth.svg", name:"mouth"},
{img: "body/neck.svg", name:"neck"},
{img: "body/nose.svg", name:"nose"},
{img: "body/palm.svg", name:"palm"},
{img: "body/shoulder.svg", name:"shoulder"},
{img: "body/stomach.svg", name:"stomach"},
{img: "body/tongue.svg", name:"tongue"},
{img: "body/wrist.svg", name:"wrist"},
// plant
{img: "plant/apple.svg", name:"apple"},
{img: "plant/bamboo.svg", name:"bamboo"},
{img: "plant/banana.svg", name:"banana"},
{img: "plant/berry.svg", name:"berry"},
{img: "plant/bush.svg", name:"bush"},
{img: "plant/coconut.svg", name:"coconut"},
{img: "plant/cucumber.svg", name:"cucumber"},
{img: "plant/eggplant.svg", name:"eggplant"},
{img: "plant/flower.svg", name:"flower\n(+do) to blossom"},
{img: "plant/grain, cereal.svg", name:"grain"},
{img: "plant/grass.svg", name:"grass"},
{img: "plant/leaf.svg", name:"leaf"},
{img: "plant/rice.svg", name:"rice"},
{img: "plant/tomato.svg", name:"tomato"},
{img: "plant/tree.svg", name:"tree"},
{img: "plant/wheat.svg", name:"wheat"},
// mental verbs
{img: "mental/agree, confirm.svg", name:"to agree, confirm\n(+causative) to persuade"},
{img: "mental/agree.svg", name:"to praise\n(+thing) praise, glory"},
{img: "mental/ask.svg", name:"to ask\n(+thing) question"},
{img: "mental/be-pessimistic.svg", name:"to despair, be pessimistic\n(+thing) despair"},
{img: "mental/believe.svg", name:"to believe, to trust\n(believe+thing) belief, trust, faith\n(false+believe) to be misled/decieved\n(false+believe+causative) to mislead, to deceive"},
{img: "mental/call.svg", name:"to call\n(+self) to be called"},
{img: "mental/choose, select.svg", name:"to choose, to select\n(choose+thing) choice, selection"},
{img: "mental/deny, negate.svg", name:"to deny, to negate\n(deny+thing) negation, denial"},
{img: "mental/deny.svg", name:"to deny, to disbelieve\n(deny+thing) denial, disbelief"},
{img: "mental/feel.svg", name:"to feel, to sense\n(feel+thing) feeling, sense, experience\n(feel+piece) a feeling, sensation, an experience\n(good+feel+thing) pleasure"},
{img: "mental/hear, listen.svg", name:"to hear\n(+thing) hearing \n(+piece) sound"},
{img: "mental/hope, be-optimistic.svg", name:"to hope, be optimistic\n(+thing) hope"},
{img: "mental/imagine.svg", name:"to imagine\n(+thing) imagination"},
{img: "mental/know, understand.svg", name:"to know, to understand\n(+thing) knowledge\n(+piece) concept, idea"},
{img: "mental/look.svg", name:"to look\n(+self) to look (like), to appear"},
{img: "mental/love.svg", name:"to love\n(+thing) love"},
{img: "mental/reject, deny.svg", name:"to scold, to boo"},
{img: "mental/remember.svg", name:"to remember, to know, to be familiar with\n(remember+thing) memory\n(remember+piece) a memory\n(remember+causative)\n(remember+passive pt.) known, famous\n(remember+passive pt.+thing) fame, reputation\n(no+) to forget\n(no+remember+thing) oblivion"},
{img: "mental/see.svg", name:"to see\n(+thing) seeing, sight"},
{img: "mental/shout.svg", name:"to shout"},
{img: "mental/sign.svg", name:"to sign, to gesture\n(+thing) sign language\n(+piece) a gesture"},
{img: "mental/sing.svg", name:"to sing\n(+thing) singing, vocals\n(+ppiece) song"},
{img: "mental/smell.svg", name:"to smell\n(+thing) smell, odour\n(+self) to smell (like)"},
{img: "mental/speak.svg", name:"to speak, to say, to tell\n(+adjective) verbal\n (+thing) speech, language\n(+piece) word\n(back+) to reply\n(back+/+thing) answer\n(+know+thing) linguistics"},
{img: "mental/taste.svg", name:"to taste\n(+thing) taste\n(+piece) flavour"},
{img: "mental/think.svg", name:"to think\n(+thing) thinking\n(+piece) thought\n(+causative) to inspire"},
{img: "mental/want, desire.svg", name:"to want, to desire"},
{img: "mental/wonder.svg", name:"to wonder\n(+thing) wonder"},
// verbs
{img: "verbs/add.svg", name:"to add\n(+thing) addition\n(+piece) addendum, summand\n(together+) to compose, to put together"},
{img: "verbs/aim, target, hunt.svg", name:"to aim, to target, to hunt\n(+thing) goal, aim, target\n(meat+) to hunt (for food)"},
{img: "verbs/attack.svg", name:"to attack\n(+thing) attack\n(+adjective) offensive"},
{img: "verbs/bend.svg", name:"to bend"},
{img: "verbs/blow.svg", name:"to blow"},
{img: "verbs/break, pause.svg", name:"to break"},
{img: "verbs/break-apart.svg", name:"to break (apart)"},
{img: "verbs/breathe.svg", name:"to breathe\n(+gas) air"},
{img: "verbs/build, construct.svg", name:"to build"},
{img: "verbs/carry.svg", name:"to carry"},
{img: "verbs/catch.svg", name:"to catch"},
{img: "verbs/chop.svg", name:"to chop"},
{img: "verbs/climb.svg", name:"to climb"},
{img: "verbs/count, calculate.svg", name:"to count, to calculate\n(+thing) calculation"},
{img: "verbs/crawl.svg", name:"to crawl"},
{img: "verbs/cry.svg", name:"to cry"},
{img: "verbs/cut.svg", name:"to cut\n(head+cut) to decapitate"},
{img: "verbs/dance.svg", name:"to dance\n(+thing) dance"},
{img: "verbs/defecate.svg", name:"to defecate"},
{img: "verbs/dive.svg", name:"to dive"},
{img: "verbs/do, function.svg", name:"to do, to function\n(frequently used suffix)"},
{img: "verbs/drink.svg", name:"to drink"},
{img: "verbs/drive.svg", name:"to drive"},
{img: "verbs/drop.svg", name:"to drop"},
{img: "verbs/drown, sink.svg", name:"to drown, to sink"},
{img: "verbs/dwell.svg", name:"to dwell\n(+thing) dwelling, habitat\n(close+) to be a neighbor"},
{img: "verbs/eat.svg", name:"to eat\n(+causative) to feed"},
{img: "verbs/fall.svg", name:"to fall\n(+thing) cadence"},
{img: "verbs/fight, wage war.svg", name:"to fight, to wage war\n(+thing) fight, conflict\n(big+/+thing) war"},
{img: "verbs/finish.svg", name:"to finish\n(+thing) finish"},
{img: "verbs/fly.svg", name:"to fly\n(+thing) flight, flying"},
{img: "verbs/folded-hands.svg", name:"Namaste, folded-hands\n(greeting)"},
{img: "verbs/gamble.svg", name:"to gamble\n(+thing) gambling"},
{img: "verbs/get lost.svg", name:"to get lost\n(+causative) to lose (somewhere)"},
{img: "verbs/get, receive.svg", name:"to get, to receive\n(+thing) reception, receiving, revenue"},
{img: "verbs/give.svg", name:"to give"},
{img: "verbs/greet.svg", name:"to greet\nhi / bye\ngreetings"},
{img: "verbs/handshake.svg", name:"handshake\n(formal greeting before COVID)"},
{img: "verbs/hang.svg", name:"to hang"},
{img: "verbs/have.svg", name:"to have, to possess\n(+thing) possession"},
{img: "verbs/help.svg", name:"to help, to assist, to support\n(+thing) help\n(speak+) to support verbally\n(stand+) to support (a construction)\n(carry+) to support (an activity)"},
{img: "verbs/hit.svg", name:"to hit\n(no+) to miss"},
{img: "verbs/hold.svg", name:"to hold"},
{img: "verbs/jump.svg", name:"to jump\n(+thing) jump"},
{img: "verbs/keep, defend.svg", name:"to keep, to protect\n(+thing) protection, protectorate"},
{img: "verbs/labour, toil.svg", name:"to toil, to labour\n(+thing) toil, labour, effort\n(+adjective) laborious, difficult, hard\n(+adjective+thing) difficulty\n(+no) easy, effortless"},
{img: "verbs/laugh.svg", name:"to laugh"},
{img: "verbs/lean.svg", name:"to lean"},
{img: "verbs/lick.svg", name:"to lick"},
{img: "verbs/lie.svg", name:"to lie"},
{img: "verbs/make, produce.svg", name:"to make, to produce"},
{img: "verbs/measure.svg", name:"to measure"},
{img: "verbs/point.svg", name:"to point"},
{img: "verbs/poke.svg", name:"to poke"},
{img: "verbs/pour.svg", name:"to pour"},
{img: "verbs/pray.svg", name:"to pray"},
{img: "verbs/press, squish.svg", name:"to press, to squish\n(apart+) to smash"},
{img: "verbs/pull.svg", name:"to pull"},
{img: "verbs/punch.svg", name:"to punch"},
{img: "verbs/push.svg", name:"to push"},
{img: "verbs/put.svg", name:"to put"},
{img: "verbs/read.svg", name:"to read\n(+house) library"},
{img: "verbs/remove.svg", name:"to remove\n(+thing) removal"},
{img: "verbs/ride.svg", name:"to ride"},
{img: "verbs/roll.svg", name:"to roll"},
{img: "verbs/rotate.svg", name:"to rotate"},
{img: "verbs/run.svg", name:"to run"},
{img: "verbs/search.svg", name:"to search\n(+thing) searching, investigation, research"},
{img: "verbs/share.svg", name:"to share\n(+thing) sharing"},
{img: "verbs/sit.svg", name:"to sit (down)"},
{img: "verbs/sleep.svg", name:"to sleep\n(no+) to wake up\n(small+) to nap"},
{img: "verbs/slip, slide.svg", name:"to slip, to slide"},
{img: "verbs/smoke.svg", name:"to smoke"},
{img: "verbs/sneeze.svg", name:"to sneeze"},
{img: "verbs/spit.svg", name:"to spit"},
{img: "verbs/squat.svg", name:"to squat"},
{img: "verbs/stand.svg", name:"to stand"},
{img: "verbs/start.svg", name:"to start"},
{img: "verbs/stop.svg", name:"to stop"},
{img: "verbs/stretch, pull.svg", name:"to stretch"},
{img: "verbs/strike, attack.svg", name:"to strike, to attack\n(+thing) strike"},
{img: "verbs/suck.svg", name:"to suck"},
{img: "verbs/swim.svg", name:"to swim"},
{img: "verbs/take, pick.svg", name:"to take, to pick\n(+thing) a pick, a set"},
{img: "verbs/tear-apart.svg", name:"to tear (apart)\n(+line) fissure"},
{img: "verbs/throw, cast.svg", name:"to throw"},
{img: "verbs/touch.svg", name:"to touch"},
{img: "verbs/trade.svg", name:"to trade\n(+thing) commerce\n(+adjective) commercial\n(out+) to sell\n(in+) to buy\n(in+/+thing) purchase\n(evil+) to betray\n(evil+/+thing) betrayal\n(+no) free, non-profit"},
{img: "verbs/turn.svg", name:"to turn"},
{img: "verbs/use.svg", name:"to use\n(+thing) use\n(+good) useful\n(+bad) useless"},
{img: "verbs/vomit.svg", name:"to vomit"},
{img: "verbs/wait.svg", name:"to wait"},
{img: "verbs/walk, go.svg", name:"to go, to walk\n(foot+) to walk"},
{img: "verbs/win, triumph.svg", name:"to win, to triumph\n(+thing) victory"},
{img: "verbs/write.svg", name:"to write\n(+thing) writing, script"},
// derivation
{img: "derivations/active.svg", name:"active participle\n-ing"},
{img: "derivations/adverb, derivate.svg", name:"(adverb suffix)\n-ly\n-wise"},
{img: "derivations/causative.svg", name:"(causative suffix)\n-ify\n-ize"},
{img: "derivations/derivation, measure.svg", name:"measure, value (derivation)\n(unused)"},
{img: "derivations/more.svg", name:"comparative\nmore, -er"},
{img: "derivations/most.svg", name:"superlative\nmost, -est"},
{img: "derivations/passive.svg", name:"passive participle\n-ed"},
{img: "derivations/rich (derivation).svg", name:"(suffix meaning rich on)\n -ous"},
{img: "derivations/worthy (derivation).svg", name:"(suffix meaning worthy of)\n -worthy"},
// misc
{img: "misc/AND.svg", name:"AND"},
{img: "misc/BUT.svg", name:"BUT"},
{img: "misc/FUT.svg", name:"Future tense suffix", half: true},
{img: "misc/INF.svg", name:"Infinitive suffix", half: true},
{img: "misc/OR.svg", name:"OR"},
{img: "misc/PLURAL.svg", name:"Plural suffix", half: true},
{img: "misc/PRES.svg", name:"Present tense suffix", half: true},
{img: "misc/PST.svg", name:"Past tense suffix", half: true},
// pronouns
{img: "pronoun/all.svg", name:"all"},
{img: "pronoun/any, multiplication.svg", name:"any\n(also used as a number suffix):\n(big+) many\n(1+) single\n(2+) pair\n(small+) few"},
{img: "pronoun/each-other.svg", name:"each-other"},
{img: "pronoun/every.svg", name:"every, each"},
{img: "pronoun/how.svg", name:"how\n(way, manner, state)\n*depicts a user manual"},
{img: "pronoun/if.svg", name:"if, whether\n(+thing) condition"},
{img: "pronoun/me.svg", name:"me"},
{img: "pronoun/necessary.svg", name:"necessary, must, must be that\n(+thing) necessity"},
{img: "pronoun/no.svg", name:"no\ndon't\n(also used as a pefix meaning privation) -less\n(also used as a suffix meaning the opposite) -un"},
{img: "pronoun/possibly.svg", name:"possibly, can, can be that\n(+thing) possibility"},
{img: "pronoun/self.svg", name:"self"},
{img: "pronoun/some.svg", name:"some"},
{img: "pronoun/that.svg", name:"that"},
{img: "pronoun/this.svg", name:"this"},
{img: "pronoun/we.svg", name:"we"},
{img: "pronoun/what.svg", name:"what\n-what"},
{img: "pronoun/when.svg", name:"when\n-when"},
{img: "pronoun/where.svg", name:"where\n-where"},
{img: "pronoun/who.svg", name:"who\n-body / -one"},
{img: "pronoun/you, thou.svg", name:"you (one)"},
{img: "pronoun/you, yall.svg", name:"you (all)"},
// alphabet
{img: "alphabet/a.svg", name:"a"},
{img: "alphabet/b.svg", name:"b"},
{img: "alphabet/c.svg", name:"c"},
{img: "alphabet/d.svg", name:"d"},
{img: "alphabet/e.svg", name:"e"},
{img: "alphabet/f.svg", name:"f"},
{img: "alphabet/g.svg", name:"g"},
{img: "alphabet/h.svg", name:"h"},
{img: "alphabet/i.svg", name:"i"},
{img: "alphabet/j.svg", name:"j"},
{img: "alphabet/k.svg", name:"k"},
{img: "alphabet/l.svg", name:"l"},
{img: "alphabet/m.svg", name:"m"},
{img: "alphabet/n.svg", name:"n"},
{img: "alphabet/o.svg", name:"o"},
{img: "alphabet/p.svg", name:"p"},
{img: "alphabet/q.svg", name:"q"},
{img: "alphabet/r.svg", name:"r"},
{img: "alphabet/s.svg", name:"s"},
{img: "alphabet/t.svg", name:"t"},
{img: "alphabet/u.svg", name:"u"},
{img: "alphabet/v.svg", name:"v"},
{img: "alphabet/w.svg", name:"w"},
{img: "alphabet/x.svg", name:"x"},
{img: "alphabet/y.svg", name:"y"},
{img: "alphabet/z.svg", name:"z"},
// punct
{img: "punct/closing-quote.svg", name:"closing-quote"},
{img: "punct/colon.svg", name:"colon"},
{img: "punct/comma.svg", name:"comma"},
{img: "punct/ex-mark.svg", name:"ex-mark"},
{img: "punct/open-quote.svg", name:"open-quote"},
{img: "punct/period.svg", name:"period"},
{img: "punct/q-mark.svg", name:"q-mark"},
{img: "punct/semicolon.svg", name:"semicolon"},
{img: "punct/space.svg", name:"space"},
];