data = [
{img: "across, through.svg", name:"across"},
{img: "active.svg", name:"active"},
{img: "add.svg", name:"add"},
{img: "adverb, derivate.svg", name:"adverb"},
{img: "afraid.svg", name:"afraid"},
{img: "after, behind.svg", name:"after"},
{img: "again, for.svg", name:"again"},
{img: "against.svg", name:"against"},
{img: "agree, confirm.svg", name:"agree"},
{img: "agree.svg", name:"agree"},
{img: "aim, target, hunt.svg", name:"aim"},
{img: "alive.svg", name:"alive"},
{img: "all.svg", name:"all"},
{img: "along.svg", name:"along"},
{img: "AND.svg", name:"AND"},
{img: "angle, corner.svg", name:"angle"},
{img: "angry.svg", name:"angry"},
{img: "any, multiplication.svg", name:"any"},
{img: "apart.svg", name:"apart"},
{img: "apple.svg", name:"apple"},
{img: "arc.svg", name:"arc"},
{img: "arm.svg", name:"arm"},
{img: "arms.svg", name:"arms"},
{img: "around.svg", name:"around"},
{img: "arrow.svg", name:"arrow"},
{img: "ask.svg", name:"ask"},
{img: "attack.svg", name:"attack"},
{img: "autumn.svg", name:"autumn"},
{img: "axe.svg", name:"axe"},
{img: "baby.svg", name:"baby"},
{img: "back, backward.svg", name:"back"},
{img: "bad.svg", name:"bad"},
{img: "banana.svg", name:"banana"},
{img: "battery.svg", name:"battery"},
{img: "be, exist.svg", name:"be"},
{img: "be-pessimistic.svg", name:"be-pessimistic"},
{img: "beautiful.svg", name:"beautiful"},
{img: "before.svg", name:"before"},
{img: "believe.svg", name:"believe"},
{img: "bend.svg", name:"bend"},
{img: "berry.svg", name:"berry"},
{img: "between, among.svg", name:"between"},
{img: "big.svg", name:"big"},
{img: "black.svg", name:"black"},
{img: "blood.svg", name:"blood"},
{img: "blow.svg", name:"blow"},
{img: "blue.svg", name:"blue"},
{img: "body.svg", name:"body"},
{img: "bored.svg", name:"bored"},
{img: "bottle.svg", name:"bottle"},
{img: "bottom.svg", name:"bottom"},
{img: "bow.svg", name:"bow"},
{img: "boy.svg", name:"boy"},
{img: "brain.svg", name:"brain"},
{img: "break, pause.svg", name:"break"},
{img: "break-apart.svg", name:"break-apart"},
{img: "breathe.svg", name:"breathe"},
{img: "brick.svg", name:"brick"},
{img: "bright.svg", name:"bright"},
{img: "brother.svg", name:"brother"},
{img: "brown.svg", name:"brown"},
{img: "brush.svg", name:"brush"},
{img: "bush.svg", name:"bush"},
{img: "BUT.svg", name:"BUT"},
{img: "call.svg", name:"call"},
{img: "calm.svg", name:"calm"},
{img: "card.svg", name:"card"},
{img: "cat.svg", name:"cat"},
{img: "catch.svg", name:"catch"},
{img: "causative.svg", name:"causative"},
{img: "ceiling.svg", name:"ceiling"},
{img: "channel.svg", name:"channel"},
{img: "child.svg", name:"child"},
{img: "choose, select.svg", name:"choose"},
{img: "circle.svg", name:"circle"},
{img: "city.svg", name:"city"},
{img: "clay.svg", name:"clay"},
{img: "climb.svg", name:"climb"},
{img: "clocks.svg", name:"clocks"},
{img: "close.svg", name:"close"},
{img: "closed.svg", name:"closed"},
{img: "cloud.svg", name:"cloud"},
{img: "coal.svg", name:"coal"},
{img: "coconut.svg", name:"coconut"},
{img: "coin.svg", name:"coin"},
{img: "cold.svg", name:"cold"},
{img: "color.svg", name:"color"},
{img: "cook.svg", name:"cook"},
{img: "cool, confident.svg", name:"cool"},
{img: "crawl.svg", name:"crawl"},
{img: "crowd, mob.svg", name:"crowd"},
{img: "cry.svg", name:"cry"},
{img: "cube.svg", name:"cube"},
{img: "cucumber.svg", name:"cucumber"},
{img: "cut.svg", name:"cut"},
{img: "cyllinder.svg", name:"cyllinder"},
{img: "dad, father.svg", name:"dad"},
{img: "dance.svg", name:"dance"},
{img: "dark.svg", name:"dark"},
{img: "date.svg", name:"date"},
{img: "day.svg", name:"day"},
{img: "daynight.svg", name:"daynight"},
{img: "dead.svg", name:"dead"},
{img: "deer.svg", name:"deer"},
{img: "defecate.svg", name:"defecate"},
{img: "delirious.svg", name:"delirious"},
{img: "demon.svg", name:"demon"},
{img: "dense.svg", name:"dense"},
{img: "deny, negate.svg", name:"deny"},
{img: "deny.svg", name:"deny"},
{img: "derivate, adjective.svg", name:"derivate"},
{img: "derivation, measure.svg", name:"derivation"},
{img: "desert.svg", name:"desert"},
{img: "dice.svg", name:"dice"},
{img: "different, other.svg", name:"different"},
{img: "dim.svg", name:"dim"},
{img: "direct, stright.svg", name:"direct"},
{img: "dirty, tainted.svg", name:"dirty"},
{img: "divide.svg", name:"divide"},
{img: "do, function.svg", name:"do"},
{img: "doctor.svg", name:"doctor"},
{img: "dog.svg", name:"dog"},
{img: "dot, point.svg", name:"dot"},
{img: "doubt.svg", name:"doubt"},
{img: "down.svg", name:"down"},
{img: "drink.svg", name:"drink"},
{img: "drive.svg", name:"drive"},
{img: "drop-1.svg", name:"drop-1"},
{img: "drop.svg", name:"drop"},
{img: "dry.svg", name:"dry"},
{img: "dwell.svg", name:"dwell"},
{img: "each-other.svg", name:"each-other"},
{img: "ear.svg", name:"ear"},
{img: "eat.svg", name:"eat"},
{img: "eggplant.svg", name:"eggplant"},
{img: "elbow.svg", name:"elbow"},
{img: "electricity.svg", name:"electricity"},
{img: "empty.svg", name:"empty"},
{img: "empty_box.svg", name:"empty_box"},
{img: "enamorado.svg", name:"enamorado"},
{img: "eternity.svg", name:"eternity"},
{img: "every.svg", name:"every"},
{img: "evil, malevolent.svg", name:"evil"},
{img: "eye-brow.svg", name:"eye-brow"},
{img: "eye-pupil.svg", name:"eye-pupil"},
{img: "eye.svg", name:"eye"},
{img: "eyelash-1.svg", name:"eyelash-1"},
{img: "eyelash.svg", name:"eyelash"},
{img: "false, no.svg", name:"false"},
{img: "family.svg", name:"family"},
{img: "far.svg", name:"far"},
{img: "farmer.svg", name:"farmer"},
{img: "fast.svg", name:"fast"},
{img: "feel.svg", name:"feel"},
{img: "finger.svg", name:"finger"},
{img: "fire.svg", name:"fire"},
{img: "fist.svg", name:"fist"},
{img: "flamingo.svg", name:"flamingo"},
{img: "floor.svg", name:"floor"},
{img: "floppy.svg", name:"floppy"},
{img: "flower.svg", name:"flower"},
{img: "fly.svg", name:"fly"},
{img: "folded-hands.svg", name:"folded-hands"},
{img: "forest.svg", name:"forest"},
{img: "fork.svg", name:"fork"},
{img: "forth, forward.svg", name:"forth"},
{img: "fragile.svg", name:"fragile"},
{img: "free, loose.svg", name:"free"},
{img: "frequent, prevalent.svg", name:"frequent"},
{img: "fresh.svg", name:"fresh"},
{img: "friend.svg", name:"friend"},
{img: "from, of, because.svg", name:"from"},
{img: "full.svg", name:"full"},
{img: "gamble.svg", name:"gamble"},
{img: "gas.svg", name:"gas"},
{img: "get, receive.svg", name:"get"},
{img: "girl.svg", name:"girl"},
{img: "give.svg", name:"give"},
{img: "globe.svg", name:"globe"},
{img: "god.svg", name:"god"},
{img: "good.svg", name:"good"},
{img: "grass.svg", name:"grass"},
{img: "greedy.svg", name:"greedy"},
{img: "green.svg", name:"green"},
{img: "greet.svg", name:"greet"},
{img: "grey.svg", name:"grey"},
{img: "grid.svg", name:"grid"},
{img: "hag.svg", name:"hag"},
{img: "hammer.svg", name:"hammer"},
{img: "hand.svg", name:"hand"},
{img: "handshake.svg", name:"handshake"},
{img: "hang.svg", name:"hang"},
{img: "happy.svg", name:"happy"},
{img: "have.svg", name:"have"},
{img: "head.svg", name:"head"},
{img: "healthy.svg", name:"healthy"},
{img: "hear, listen.svg", name:"hear"},
{img: "heart.svg", name:"heart"},
{img: "heavy.svg", name:"heavy"},
{img: "help.svg", name:"help"},
{img: "hold.svg", name:"hold"},
{img: "home, house.svg", name:"home"},
{img: "hope, be-optimistic.svg", name:"hope"},
{img: "hot.svg", name:"hot"},
{img: "how.svg", name:"how"},
{img: "hungry, thirsty.svg", name:"hungry"},
{img: "if.svg", name:"if"},
{img: "imagine.svg", name:"imagine"},
{img: "in, into.svg", name:"in"},
{img: "indirect.svg", name:"indirect"},
{img: "INF.svg", name:"INF"},
{img: "iron, steel.svg", name:"iron"},
{img: "island.svg", name:"island"},
{img: "jigsaw, puzzle.svg", name:"jigsaw"},
{img: "jump.svg", name:"jump"},
{img: "keep, defend.svg", name:"keep"},
{img: "kid.svg", name:"kid"},
{img: "knife.svg", name:"knife"},
{img: "know, understand.svg", name:"know"},
{img: "land.svg", name:"land"},
{img: "leaf.svg", name:"leaf"},
{img: "lean.svg", name:"lean"},
{img: "left.svg", name:"left"},
{img: "leg.svg", name:"leg"},
{img: "lick.svg", name:"lick"},
{img: "lie.svg", name:"lie"},
{img: "light.svg", name:"light"},
{img: "lightbulb.svg", name:"lightbulb"},
{img: "line.svg", name:"line"},
{img: "liquid.svg", name:"liquid"},
{img: "long.svg", name:"long"},
{img: "look.svg", name:"look"},
{img: "loud.svg", name:"loud"},
{img: "love.svg", name:"love"},
{img: "luck.svg", name:"luck"},
{img: "lungs.svg", name:"lungs"},
{img: "man.svg", name:"man"},
{img: "map.svg", name:"map"},
{img: "me.svg", name:"me"},
{img: "measure.svg", name:"measure"},
{img: "mighty, powerful.svg", name:"mighty"},
{img: "minus.svg", name:"minus"},
{img: "mom, mother.svg", name:"mom"},
{img: "monarch.svg", name:"monarch"},
{img: "money.svg", name:"money"},
{img: "month.svg", name:"month"},
{img: "moon, crescent.svg", name:"moon"},
{img: "more.svg", name:"more"},
{img: "morning.svg", name:"morning"},
{img: "most.svg", name:"most"},
{img: "mountain.svg", name:"mountain"},
{img: "mouth.svg", name:"mouth"},
{img: "music.svg", name:"music"},
{img: "n1.svg", name:"n1"},
{img: "n2.svg", name:"n2"},
{img: "n3.svg", name:"n3"},
{img: "n4.svg", name:"n4"},
{img: "n5.svg", name:"n5"},
{img: "n6.svg", name:"n6"},
{img: "n7.svg", name:"n7"},
{img: "n8.svg", name:"n8"},
{img: "n9.svg", name:"n9"},
{img: "name.svg", name:"name"},
{img: "narrow (thin).svg", name:"narrow (thin)"},
{img: "necessary.svg", name:"necessary"},
{img: "new.svg", name:"new"},
{img: "next.svg", name:"next"},
{img: "night.svg", name:"night"},
{img: "no.svg", name:"no"},
{img: "nose.svg", name:"nose"},
{img: "noun, derivate.svg", name:"noun"},
{img: "oak_.svg", name:"oak_"},
{img: "of.svg", name:"of"},
{img: "off.svg", name:"off"},
{img: "old.svg", name:"old"},
{img: "on, upon.svg", name:"on"},
{img: "open.svg", name:"open"},
{img: "OR.svg", name:"OR"},
{img: "out, outside.svg", name:"out"},
{img: "oval.svg", name:"oval"},
{img: "over, above.svg", name:"over"},
{img: "palm.svg", name:"palm"},
{img: "parent.svg", name:"parent"},
{img: "passive.svg", name:"passive"},
{img: "people.svg", name:"people"},
{img: "perfect.svg", name:"perfect"},
{img: "person.svg", name:"person"},
{img: "pickaxe.svg", name:"pickaxe"},
{img: "piece, part.svg", name:"piece"},
{img: "pink.svg", name:"pink"},
{img: "place.svg", name:"place"},
{img: "plane, flat.svg", name:"plane"},
{img: "planet, world.svg", name:"planet"},
{img: "plus.svg", name:"plus"},
{img: "poison, venom, toxin.svg", name:"poison"},
{img: "poke.svg", name:"poke"},
{img: "poop.svg", name:"poop"},
{img: "possibly.svg", name:"possibly"},
{img: "pour.svg", name:"pour"},
{img: "PRES.svg", name:"PRES"},
{img: "press, squish.svg", name:"press"},
{img: "previous.svg", name:"previous"},
{img: "prisoner, inmate.svg", name:"prisoner"},
{img: "PST.svg", name:"PST"},
{img: "pull.svg", name:"pull"},
{img: "punch.svg", name:"punch"},
{img: "push.svg", name:"push"},
{img: "put.svg", name:"put"},
{img: "quiet.svg", name:"quiet"},
{img: "rain.svg", name:"rain"},
{img: "rake.svg", name:"rake"},
{img: "random.svg", name:"random"},
{img: "rare, infrequent.svg", name:"rare"},
{img: "raven.svg", name:"raven"},
{img: "red.svg", name:"red"},
{img: "reject, deny.svg", name:"reject"},
{img: "relationships.svg", name:"relationships"},
{img: "remember.svg", name:"remember"},
{img: "remove.svg", name:"remove"},
{img: "rhombus.svg", name:"rhombus"},
{img: "rich (derivation).svg", name:"rich (derivation)"},
{img: "rich.svg", name:"rich"},
{img: "ride.svg", name:"ride"},
{img: "right.svg", name:"right"},
{img: "river, stream.svg", name:"river"},
{img: "road.svg", name:"road"},
{img: "rotate.svg", name:"rotate"},
{img: "round.svg", name:"round"},
{img: "ruler.svg", name:"ruler"},
{img: "run.svg", name:"run"},
{img: "sad.svg", name:"sad"},
{img: "same, equal.svg", name:"same"},
{img: "scales.svg", name:"scales"},
{img: "scythe.svg", name:"scythe"},
{img: "sea, ocean.svg", name:"sea"},
{img: "search.svg", name:"search"},
{img: "see.svg", name:"see"},
{img: "self.svg", name:"self"},
{img: "shape.svg", name:"shape"},
{img: "share.svg", name:"share"},
{img: "sharp.svg", name:"sharp"},
{img: "shield.svg", name:"shield"},
{img: "short(low).svg", name:"short(low)"},
{img: "short.svg", name:"short"},
{img: "shoulder.svg", name:"shoulder"},
{img: "shout.svg", name:"shout"},
{img: "sibling.svg", name:"sibling"},
{img: "sick.svg", name:"sick"},
{img: "sign.svg", name:"sign"},
{img: "silent.svg", name:"silent"},
{img: "silly.svg", name:"silly"},
{img: "similar, alike.svg", name:"similar"},
{img: "sing.svg", name:"sing"},
{img: "sister.svg", name:"sister"},
{img: "sit.svg", name:"sit"},
{img: "sky, heavens.svg", name:"sky"},
{img: "sleep.svg", name:"sleep"},
{img: "slip, slide.svg", name:"slip"},
{img: "slow.svg", name:"slow"},
{img: "small.svg", name:"small"},
{img: "smart.svg", name:"smart"},
{img: "smell.svg", name:"smell"},
{img: "smoke.svg", name:"smoke"},
{img: "sneeze.svg", name:"sneeze"},
{img: "soft.svg", name:"soft"},
{img: "soil, dirt.svg", name:"soil"},
{img: "solid, hard.svg", name:"solid"},
{img: "some.svg", name:"some"},
{img: "space-1.svg", name:"space-1"},
{img: "spade, shovel.svg", name:"spade"},
{img: "speak.svg", name:"speak"},
{img: "spear.svg", name:"spear"},
{img: "sphere, ball.svg", name:"sphere"},
{img: "spirit, ghost.svg", name:"spirit"},
{img: "spit.svg", name:"spit"},
{img: "spoon.svg", name:"spoon"},
{img: "spotted, dotted.svg", name:"spotted"},
{img: "spring.svg", name:"spring"},
{img: "square.svg", name:"square"},
{img: "squat.svg", name:"squat"},
{img: "stair.svg", name:"stair"},
{img: "stand.svg", name:"stand"},
{img: "start.svg", name:"start"},
{img: "steering-wheel.svg", name:"steering-wheel"},
{img: "sticky, viscous.svg", name:"sticky"},
{img: "stone, rock.svg", name:"stone"},
{img: "stop.svg", name:"stop"},
{img: "stopwatch.svg", name:"stopwatch"},
{img: "stretch, pull.svg", name:"stretch"},
{img: "strike, attack.svg", name:"strike"},
{img: "striped.svg", name:"striped"},
{img: "strong.svg", name:"strong"},
{img: "suck.svg", name:"suck"},
{img: "summer.svg", name:"summer"},
{img: "sun.svg", name:"sun"},
{img: "sunrise.svg", name:"sunrise"},
{img: "sunset.svg", name:"sunset"},
{img: "surprised.svg", name:"surprised"},
{img: "swim.svg", name:"swim"},
{img: "sword.svg", name:"sword"},
{img: "take, pick.svg", name:"take"},
{img: "tall.svg", name:"tall"},
{img: "taste.svg", name:"taste"},
{img: "tear-apart.svg", name:"tear-apart"},
{img: "that.svg", name:"that"},
{img: "thick (wide).svg", name:"thick (wide)"},
{img: "thing.svg", name:"thing"},
{img: "think.svg", name:"think"},
{img: "this.svg", name:"this"},
{img: "throw, cast.svg", name:"throw"},
{img: "tile.svg", name:"tile"},
{img: "time.svg", name:"time"},
{img: "times, multiply.svg", name:"times"},
{img: "to, at, for.svg", name:"to"},
{img: "together.svg", name:"together"},
{img: "tomato.svg", name:"tomato"},
{img: "tongue.svg", name:"tongue"},
{img: "tool.svg", name:"tool"},
{img: "top.svg", name:"top"},
{img: "torch.svg", name:"torch"},
{img: "total, whole.svg", name:"total"},
{img: "touch.svg", name:"touch"},
{img: "tree.svg", name:"tree"},
{img: "true, yes.svg", name:"true"},
{img: "turn.svg", name:"turn"},
{img: "under, below.svg", name:"under"},
{img: "up.svg", name:"up"},
{img: "village.svg", name:"village"},
{img: "vomit.svg", name:"vomit"},
{img: "wait.svg", name:"wait"},
{img: "walk.svg", name:"walk"},
{img: "wall.svg", name:"wall"},
{img: "wand.svg", name:"wand"},
{img: "want, desire.svg", name:"want"},
{img: "warm.svg", name:"warm"},
{img: "water.svg", name:"water"},
{img: "wave.svg", name:"wave"},
{img: "way, method.svg", name:"way"},
{img: "we.svg", name:"we"},
{img: "weak.svg", name:"weak"},
{img: "wet.svg", name:"wet"},
{img: "what.svg", name:"what"},
{img: "when.svg", name:"when"},
{img: "where.svg", name:"where"},
{img: "white.svg", name:"white"},
{img: "who.svg", name:"who"},
{img: "winter.svg", name:"winter"},
{img: "wolf.svg", name:"wolf"},
{img: "woman.svg", name:"woman"},
{img: "wonder.svg", name:"wonder"},
{img: "worthy (derivation).svg", name:"worthy (derivation)"},
{img: "wrench.svg", name:"wrench"},
{img: "wrist.svg", name:"wrist"},
{img: "yard.svg", name:"yard"},
{img: "year.svg", name:"year"},
{img: "yellow.svg", name:"yellow"},
{img: "you, thou.svg", name:"you"},
{img: "you, yall.svg", name:"you"},
{img: "young.svg", name:"young"}
];