data = [
// math
{img: "math/divide.svg", name:"divide"},
{img: "math/equals.svg", name:"equals"},
{img: "math/minus.svg", name:"minus"},
{img: "math/n0.svg", name:"0"},
{img: "math/n1.svg", name:"1"},
{img: "math/n2.svg", name:"2"},
{img: "math/n3.svg", name:"3"},
{img: "math/n4.svg", name:"4"},
{img: "math/n5.svg", name:"5"},
{img: "math/n6.svg", name:"6"},
{img: "math/n7.svg", name:"7"},
{img: "math/n8.svg", name:"8"},
{img: "math/n9.svg", name:"9"},
{img: "math/plus.svg", name:"plus"},
{img: "math/times, multiply.svg", name:"times"},
// arrows
{img: "arrows/across, through.svg", name:"across"},
{img: "arrows/after, behind.svg", name:"after"},
{img: "arrows/again, for.svg", name:"again"},
{img: "arrows/against.svg", name:"against"},
{img: "arrows/along.svg", name:"along"},
{img: "arrows/apart.svg", name:"apart"},
{img: "arrows/around.svg", name:"around"},
{img: "arrows/back, backward.svg", name:"back"},
{img: "arrows/before.svg", name:"before"},
{img: "arrows/between, among.svg", name:"between"},
{img: "arrows/down.svg", name:"down"},
{img: "arrows/forth, forward.svg", name:"forth"},
{img: "arrows/from, of, because.svg", name:"from"},
{img: "arrows/in, into.svg", name:"in"},
{img: "arrows/left.svg", name:"left"},
{img: "arrows/of.svg", name:"of"},
{img: "arrows/off.svg", name:"off"},
{img: "arrows/on, upon.svg", name:"on"},
{img: "arrows/out, outside.svg", name:"out"},
{img: "arrows/over, above.svg", name:"over"},
{img: "arrows/right.svg", name:"right"},
{img: "arrows/to, at, for.svg", name:"to"},
{img: "arrows/together.svg", name:"together"},
{img: "arrows/under, below.svg", name:"under"},
{img: "arrows/up.svg", name:"up"},
// evaluation
{img: "evaluation/bad.svg", name:"bad"},
{img: "evaluation/beautiful.svg", name:"beautiful"},
{img: "evaluation/different, other.svg", name:"different"},
{img: "evaluation/false, no.svg", name:"false"},
{img: "evaluation/good.svg", name:"good"},
{img: "evaluation/perfect.svg", name:"perfect"},
{img: "evaluation/same, equal.svg", name:"same"},
{img: "evaluation/similar, alike.svg", name:"similar"},
{img: "evaluation/true, yes.svg", name:"true"},
// adjectives
{img: "adjectives/big.svg", name:"big"},
{img: "adjectives/bright.svg", name:"bright"},
{img: "adjectives/closed.svg", name:"closed"},
{img: "adjectives/cold.svg", name:"cold"},
{img: "adjectives/dark.svg", name:"dark"},
{img: "adjectives/dense.svg", name:"dense"},
{img: "adjectives/dim.svg", name:"dim"},
{img: "adjectives/dry.svg", name:"dry"},
{img: "adjectives/empty.svg", name:"empty"},
{img: "adjectives/fast.svg", name:"fast"},
{img: "adjectives/femal.svg", name:"femal"},
{img: "adjectives/fragile.svg", name:"fragile"},
{img: "adjectives/free, loose.svg", name:"free"},
{img: "adjectives/frequent, prevalent.svg", name:"frequent"},
{img: "adjectives/fresh.svg", name:"fresh"},
{img: "adjectives/full.svg", name:"full"},
{img: "adjectives/gas.svg", name:"gas"},
{img: "adjectives/heavy.svg", name:"heavy"},
{img: "adjectives/hot.svg", name:"hot"},
{img: "adjectives/light.svg", name:"light"},
{img: "adjectives/liquid.svg", name:"liquid"},
{img: "adjectives/loud.svg", name:"loud"},
{img: "adjectives/male.svg", name:"male"},
{img: "adjectives/mighty, powerful.svg", name:"mighty, powerful"},
{img: "adjectives/new.svg", name:"new"},
{img: "adjectives/old.svg", name:"old"},
{img: "adjectives/open.svg", name:"open"},
{img: "adjectives/quiet.svg", name:"quiet"},
{img: "adjectives/rare, infrequent.svg", name:"rare"},
{img: "adjectives/silent.svg", name:"silent"},
{img: "adjectives/slow.svg", name:"slow"},
{img: "adjectives/small.svg", name:"small"},
{img: "adjectives/soft.svg", name:"soft"},
{img: "adjectives/solid, hard.svg", name:"solid"},
{img: "adjectives/sticky, viscous.svg", name:"sticky"},
{img: "adjectives/strong.svg", name:"strong"},
{img: "adjectives/warm.svg", name:"warm"},
{img: "adjectives/weak.svg", name:"weak"},
{img: "adjectives/wet.svg", name:"wet"},
{img: "adjectives/young.svg", name:"young"},
// faces
{img: "faces/afraid.svg", name:"afraid"},
{img: "faces/alive.svg", name:"alive"},
{img: "faces/angry.svg", name:"angry"},
{img: "faces/bored.svg", name:"bored"},
{img: "faces/calm.svg", name:"calm"},
{img: "faces/cool, confident.svg", name:"cool"},
{img: "faces/dead.svg", name:"dead"},
{img: "faces/delirious.svg", name:"delirious"},
{img: "faces/derivate, adjective.svg", name:"derivate"},
{img: "faces/doubt.svg", name:"doubt"},
{img: "faces/enamorado.svg", name:"enamorado"},
{img: "faces/evil, malevolent.svg", name:"evil"},
{img: "faces/greedy.svg", name:"greedy"},
{img: "faces/happy.svg", name:"happy"},
{img: "faces/healthy.svg", name:"healthy"},
{img: "faces/hungry, thirsty.svg", name:"hungry"},
{img: "faces/hurt, in-pain.svg", name:"hurt"},
{img: "faces/rich.svg", name:"rich"},
{img: "faces/sad.svg", name:"sad"},
{img: "faces/sick.svg", name:"sick"},
{img: "faces/silly.svg", name:"silly"},
{img: "faces/smart.svg", name:"smart"},
{img: "faces/surprised.svg", name:"surprised"},
{img: "faces/tired.svg", name:"tired"},
// abstract
{img: "abstract/be, exist.svg", name:"be"},
{img: "abstract/body.svg", name:"body"},
{img: "abstract/half.svg", name:"half"},
{img: "abstract/layer.svg", name:"layer"},
{img: "abstract/luck.svg", name:"luck"},
{img: "abstract/mind.svg", name:"mind"},
{img: "abstract/music.svg", name:"music"},
{img: "abstract/name.svg", name:"name"},
{img: "abstract/number.svg", name:"number"},
{img: "abstract/piece, part.svg", name:"piece"},
{img: "abstract/random.svg", name:"random"},
{img: "abstract/relationships.svg", name:"relationships"},
{img: "abstract/section, part.svg", name:"section"},
{img: "abstract/side.svg", name:"side"},
{img: "abstract/thing.svg", name:"thing"},
{img: "abstract/total, whole.svg", name:"total"},
{img: "abstract/wave.svg", name:"wave"},
{img: "abstract/way, method.svg", name:"way"},
// materials
{img: "materials/blood.svg", name:"blood"},
{img: "materials/bread.svg", name:"bread"},
{img: "materials/clay.svg", name:"clay"},
{img: "materials/coal.svg", name:"coal"},
{img: "materials/drop.svg", name:"drop"},
{img: "materials/electricity.svg", name:"electricity"},
{img: "materials/fire.svg", name:"fire"},
{img: "materials/gold.svg", name:"gold"},
{img: "materials/iron, steel.svg", name:"iron"},
{img: "materials/meat.svg", name:"meat"},
{img: "materials/paper.svg", name:"paper"},
{img: "materials/poop.svg", name:"poop"},
{img: "materials/soil, dirt.svg", name:"soil"},
{img: "materials/stone, rock.svg", name:"stone"},
{img: "materials/water.svg", name:"water"},
// shapes
{img: "shapes/angle, corner.svg", name:"angle"},
{img: "shapes/arc.svg", name:"arc"},
{img: "shapes/bottom.svg", name:"bottom"},
{img: "shapes/circle.svg", name:"circle"},
{img: "shapes/close.svg", name:"close"},
{img: "shapes/cube.svg", name:"cube"},
{img: "shapes/cyllinder.svg", name:"cyllinder"},
{img: "shapes/direct, stright.svg", name:"direct"},
{img: "shapes/dot, point.svg", name:"dot"},
{img: "shapes/far.svg", name:"far"},
{img: "shapes/grid.svg", name:"grid"},
{img: "shapes/indirect.svg", name:"indirect"},
{img: "shapes/line.svg", name:"line"},
{img: "shapes/long.svg", name:"long"},
{img: "shapes/narrow (thin).svg", name:"narrow, thin"},
{img: "shapes/next.svg", name:"next"},
{img: "shapes/oval.svg", name:"oval"},
{img: "shapes/plane, flat.svg", name:"plane"},
{img: "shapes/previous.svg", name:"previous"},
{img: "shapes/ray.svg", name:"ray"},
{img: "shapes/rhombus.svg", name:"rhombus"},
{img: "shapes/round.svg", name:"round"},
{img: "shapes/shape.svg", name:"shape"},
{img: "shapes/sharp.svg", name:"sharp"},
{img: "shapes/short(low).svg", name:"short (low)"},
{img: "shapes/short.svg", name:"short"},
{img: "shapes/space.svg", name:"space"},
{img: "shapes/sphere, ball.svg", name:"sphere"},
{img: "shapes/square.svg", name:"square"},
{img: "shapes/tall.svg", name:"tall"},
{img: "shapes/thick (wide).svg", name:"thick, wide, broad"},
{img: "shapes/top.svg", name:"top"},
// color
{img: "color/black.svg", name:"black"},
{img: "color/blue.svg", name:"blue"},
{img: "color/brown.svg", name:"brown"},
{img: "color/clear, transparent.svg", name:"clear"},
{img: "color/color.svg", name:"color"},
{img: "color/dirty, tainted.svg", name:"dirty"},
{img: "color/green.svg", name:"green"},
{img: "color/grey.svg", name:"grey"},
{img: "color/pink.svg", name:"pink"},
{img: "color/red.svg", name:"red"},
{img: "color/spotted, dotted.svg", name:"spotted"},
{img: "color/striped.svg", name:"striped"},
{img: "color/white.svg", name:"white"},
{img: "color/yellow.svg", name:"yellow"},
// tools
{img: "tools/axe.svg", name:"axe"},
{img: "tools/broom.svg", name:"broom"},
{img: "tools/brush.svg", name:"brush"},
{img: "tools/fork.svg", name:"fork"},
{img: "tools/hammer.svg", name:"hammer"},
{img: "tools/knife.svg", name:"knife"},
{img: "tools/pickaxe.svg", name:"pickaxe"},
{img: "tools/rake.svg", name:"rake"},
{img: "tools/ruler.svg", name:"ruler"},
{img: "tools/scythe.svg", name:"scythe"},
{img: "tools/spade, shovel.svg", name:"spade"},
{img: "tools/spoon.svg", name:"spoon"},
{img: "tools/tool.svg", name:"tool"},
{img: "tools/torch.svg", name:"torch"},
{img: "tools/wand.svg", name:"wand"},
{img: "tools/wrench.svg", name:"wrench"},
// items
{img: "items/arms.svg", name:"arms"},
{img: "items/arrow.svg", name:"arrow"},
{img: "items/battery.svg", name:"battery"},
{img: "items/boat.svg", name:"boat"},
{img: "items/book.svg", name:"book"},
{img: "items/bottle.svg", name:"bottle"},
{img: "items/bow.svg", name:"bow"},
{img: "items/brick.svg", name:"brick"},
{img: "items/card.svg", name:"card"},
{img: "items/cart, car.svg", name:"cart"},
{img: "items/clocks.svg", name:"clocks"},
{img: "items/coin.svg", name:"coin"},
{img: "items/compass.svg", name:"compass"},
{img: "items/dice.svg", name:"dice"},
{img: "items/floppy.svg", name:"floppy"},
{img: "items/globe.svg", name:"globe"},
{img: "items/jigsaw, puzzle.svg", name:"jigsaw"},
{img: "items/lightbulb.svg", name:"lightbulb"},
{img: "items/map.svg", name:"map"},
{img: "items/money.svg", name:"money"},
{img: "items/painting.svg", name:"painting"},
{img: "items/pedestal.svg", name:"pedestal"},
{img: "items/poison, venom, toxin.svg", name:"poison"},
{img: "items/scales.svg", name:"scales"},
{img: "items/shield.svg", name:"shield"},
{img: "items/spear.svg", name:"spear"},
{img: "items/steering-wheel.svg", name:"steering wheel"},
{img: "items/stopwatch.svg", name:"stopwatch"},
{img: "items/sword.svg", name:"sword"},
{img: "items/target.svg", name:"target"},
{img: "items/tea.svg", name:"tea"},
{img: "items/thread.svg", name:"thread"},
// place
{img: "place/ceiling.svg", name:"ceiling"},
{img: "place/channel.svg", name:"channel"},
{img: "place/city.svg", name:"city"},
{img: "place/desert.svg", name:"desert"},
{img: "place/door.svg", name:"door"},
{img: "place/east.svg", name:"east"},
{img: "place/field.svg", name:"field"},
{img: "place/floor.svg", name:"floor"},
{img: "place/forest.svg", name:"forest"},
{img: "place/gates.svg", name:"gates"},
{img: "place/home, house.svg", name:"home"},
{img: "place/island.svg", name:"island"},
{img: "place/land.svg", name:"land"},
{img: "place/mountain.svg", name:"mountain"},
{img: "place/north.svg", name:"north"},
{img: "place/place.svg", name:"place"},
{img: "place/river, stream.svg", name:"river"},
{img: "place/road.svg", name:"road"},
{img: "place/room.svg", name:"room"},
{img: "place/sea, ocean.svg", name:"sea"},
{img: "place/south.svg", name:"south"},
{img: "place/stair.svg", name:"stair"},
{img: "place/store.svg", name:"store"},
{img: "place/temple.svg", name:"temple"},
{img: "place/tile.svg", name:"tile"},
{img: "place/valley.svg", name:"valley"},
{img: "place/village.svg", name:"village"},
{img: "place/wall.svg", name:"wall"},
{img: "place/west.svg", name:"west"},
{img: "place/woods.svg", name:"woods"},
{img: "place/yard.svg", name:"yard"},
// sky
{img: "sky/cloud.svg", name:"cloud"},
{img: "sky/moon, crescent.svg", name:"moon"},
{img: "sky/planet, world.svg", name:"planet"},
{img: "sky/rain.svg", name:"rain"},
{img: "sky/sky, heavens.svg", name:"sky"},
{img: "sky/snow.svg", name:"snow"},
{img: "sky/star.svg", name:"star"},
{img: "sky/sun.svg", name:"sun"},
{img: "sky/wind.svg", name:"wind"},
// time
{img: "time/autumn.svg", name:"autumn"},
{img: "time/date.svg", name:"date"},
{img: "time/day.svg", name:"day"},
{img: "time/daynight.svg", name:"daynight"},
{img: "time/eternity.svg", name:"eternity"},
{img: "time/evening.svg", name:"evening"},
{img: "time/hour.svg", name:"hour"},
{img: "time/minute.svg", name:"minute"},
{img: "time/month.svg", name:"month"},
{img: "time/morning.svg", name:"morning"},
{img: "time/night.svg", name:"night"},
{img: "time/secund.svg", name:"secund"},
{img: "time/spring.svg", name:"spring"},
{img: "time/summer.svg", name:"summer"},
{img: "time/sunrise.svg", name:"sunrise"},
{img: "time/sunset.svg", name:"sunset"},
{img: "time/time.svg", name:"time"},
{img: "time/week.svg", name:"week"},
{img: "time/winter.svg", name:"winter"},
{img: "time/year.svg", name:"year"},
// people
{img: "people/baby.svg", name:"baby"},
{img: "people/boy.svg", name:"boy"},
{img: "people/brother.svg", name:"brother"},
{img: "people/child.svg", name:"child"},
{img: "people/cook.svg", name:"cook"},
{img: "people/crowd, mob.svg", name:"crowd"},
{img: "people/dad, father.svg", name:"dad"},
{img: "people/demon.svg", name:"demon"},
{img: "people/doctor.svg", name:"doctor"},
{img: "people/family.svg", name:"family"},
{img: "people/farmer.svg", name:"farmer"},
{img: "people/friend.svg", name:"friend"},
{img: "people/girl.svg", name:"girl"},
{img: "people/god.svg", name:"god"},
{img: "people/hag.svg", name:"elder"},
{img: "people/kid.svg", name:"kid"},
{img: "people/man.svg", name:"man"},
{img: "people/mom, mother.svg", name:"mom"},
{img: "people/monarch.svg", name:"monarch"},
{img: "people/parent.svg", name:"parent"},
{img: "people/people.svg", name:"people"},
{img: "people/person.svg", name:"person"},
{img: "people/prisoner, inmate.svg", name:"prisoner"},
{img: "people/sibling.svg", name:"sibling"},
{img: "people/sister.svg", name:"sister"},
{img: "people/spirit, ghost.svg", name:"spirit"},
{img: "people/student.svg", name:"student"},
{img: "people/woman.svg", name:"woman"},
// animals
{img: "animals/bee.svg", name:"bee"},
{img: "animals/bird.svg", name:"bird"},
{img: "animals/bug.svg", name:"bug"},
{img: "animals/cat.svg", name:"cat"},
{img: "animals/chicken.svg", name:"chicken"},
{img: "animals/chirp.svg", name:"chirp"},
{img: "animals/cow.svg", name:"cow"},
{img: "animals/deer.svg", name:"deer"},
{img: "animals/dog.svg", name:"dog"},
{img: "animals/feather.svg", name:"feather"},
{img: "animals/fish.svg", name:"fish"},
{img: "animals/flamingo.svg", name:"flamingo"},
{img: "animals/grasshopper.svg", name:"grasshopper"},
{img: "animals/horse.svg", name:"horse"},
{img: "animals/insect.svg", name:"insect"},
{img: "animals/raven.svg", name:"raven"},
{img: "animals/shellfish.svg", name:"shellfish"},
{img: "animals/wolf.svg", name:"wolf"},
// body parts
{img: "body/arm.svg", name:"arm"},
{img: "body/brain.svg", name:"brain"},
{img: "body/ear.svg", name:"ear"},
{img: "body/elbow.svg", name:"elbow"},
{img: "body/eye-brow.svg", name:"eyebrow"},
{img: "body/eye-pupil.svg", name:"pupil"},
{img: "body/eye.svg", name:"eye"},
{img: "body/eyelash-1.svg", name:"eyelid"},
{img: "body/eyelash.svg", name:"eyelash"},
{img: "body/face.svg", name:"face"},
{img: "body/finger.svg", name:"finger"},
{img: "body/fist.svg", name:"fist"},
{img: "body/foot.svg", name:"foot"},
{img: "body/hair.svg", name:"hair"},
{img: "body/hand.svg", name:"hand"},
{img: "body/head.svg", name:"head"},
{img: "body/heart.svg", name:"heart"},
{img: "body/heel.svg", name:"heel"},
{img: "body/knee.svg", name:"knee"},
{img: "body/leg.svg", name:"leg"},
{img: "body/lungs.svg", name:"lungs"},
{img: "body/mouth.svg", name:"mouth"},
{img: "body/neck.svg", name:"neck"},
{img: "body/nose.svg", name:"nose"},
{img: "body/palm.svg", name:"palm"},
{img: "body/shoulder.svg", name:"shoulder"},
{img: "body/tongue.svg", name:"tongue"},
{img: "body/wrist.svg", name:"wrist"},

// plant
{img: "plant/apple.svg", name:"apple"},
{img: "plant/bamboo.svg", name:"bamboo"},
{img: "plant/banana.svg", name:"banana"},
{img: "plant/berry.svg", name:"berry"},
{img: "plant/bush.svg", name:"bush"},
{img: "plant/coconut.svg", name:"coconut"},
{img: "plant/cucumber.svg", name:"cucumber"},
{img: "plant/eggplant.svg", name:"eggplant"},
{img: "plant/flower.svg", name:"flower"},
{img: "plant/grain, cereal.svg", name:"grain"},
{img: "plant/grass.svg", name:"grass"},
{img: "plant/leaf.svg", name:"leaf"},
{img: "plant/rice.svg", name:"rice"},
{img: "plant/tomato.svg", name:"tomato"},
{img: "plant/tree.svg", name:"tree"},
{img: "plant/wheat.svg", name:"wheat"},
// mental verbs
{img: "mental/agree, confirm.svg", name:"to agree, confirm"},
{img: "mental/agree.svg", name:"to agree"},
{img: "mental/ask.svg", name:"to ask"},
{img: "mental/be-pessimistic.svg", name:"to despair, be pessimistic"},
{img: "mental/believe.svg", name:"to believe"},
{img: "mental/call.svg", name:"to call"},
{img: "mental/choose, select.svg", name:"to choose"},
{img: "mental/deny, negate.svg", name:"to deny, negate"},
{img: "mental/deny.svg", name:"to deny"},
{img: "mental/feel.svg", name:"to feel"},
{img: "mental/hear, listen.svg", name:"to hear"},
{img: "mental/hope, be-optimistic.svg", name:"to hope, be optimistic"},
{img: "mental/imagine.svg", name:"to imagine"},
{img: "mental/know, understand.svg", name:"to know"},
{img: "mental/look.svg", name:"to look"},
{img: "mental/love.svg", name:"to love"},
{img: "mental/reject, deny.svg", name:"to reject"},
{img: "mental/remember.svg", name:"to remember"},
{img: "mental/see.svg", name:"to see"},
{img: "mental/shout.svg", name:"to shout"},
{img: "mental/sign.svg", name:"to sign"},
{img: "mental/sing.svg", name:"to sing"},
{img: "mental/smell.svg", name:"to smell"},
{img: "mental/speak.svg", name:"to speak"},
{img: "mental/taste.svg", name:"to taste"},
{img: "mental/think.svg", name:"to think"},
{img: "mental/want, desire.svg", name:"to want"},
{img: "mental/wonder.svg", name:"to wonder"},
// verbs
{img: "verbs/add.svg", name:"to add"},
{img: "verbs/aim, target, hunt.svg", name:"to aim"},
{img: "verbs/attack.svg", name:"to attack"},
{img: "verbs/bend.svg", name:"to bend"},
{img: "verbs/blow.svg", name:"to blow"},
{img: "verbs/break, pause.svg", name:"to break, pause"},
{img: "verbs/break-apart.svg", name:"to break (apart)"},
{img: "verbs/breathe.svg", name:"to breathe"},
{img: "verbs/carry.svg", name:"to carry"},
{img: "verbs/catch.svg", name:"to catch"},
{img: "verbs/climb.svg", name:"to climb"},
{img: "verbs/count, calculate.svg", name:"to count"},
{img: "verbs/crawl.svg", name:"to crawl"},
{img: "verbs/cry.svg", name:"to cry"},
{img: "verbs/cut.svg", name:"to cut"},
{img: "verbs/dance.svg", name:"to dance"},
{img: "verbs/defecate.svg", name:"to defecate"},
{img: "verbs/do, function.svg", name:"to do"},
{img: "verbs/drink.svg", name:"to drink"},
{img: "verbs/drive.svg", name:"to drive"},
{img: "verbs/drop.svg", name:"to drop"},
{img: "verbs/drown, sink.svg", name:"to drown"},
{img: "verbs/dwell.svg", name:"to dwell"},
{img: "verbs/eat.svg", name:"to eat"},
{img: "verbs/fly.svg", name:"to fly"},
{img: "verbs/folded-hands.svg", name:"folded-hands (greeting)"},
{img: "verbs/gamble.svg", name:"to gamble"},
{img: "verbs/get, receive.svg", name:"to get"},
{img: "verbs/give.svg", name:"to give"},
{img: "verbs/greet.svg", name:"to greet (greeting)"},
{img: "verbs/handshake.svg", name:"handshake (greeting)"},
{img: "verbs/hang.svg", name:"to hang"},
{img: "verbs/have.svg", name:"to have"},
{img: "verbs/help.svg", name:"to help"},
{img: "verbs/hit.svg", name:"to hit"},
{img: "verbs/hold.svg", name:"to hold"},
{img: "verbs/jump.svg", name:"to jump"},
{img: "verbs/keep, defend.svg", name:"to keep"},
{img: "verbs/labour, toil.svg", name:"to labour"},
{img: "verbs/lean.svg", name:"to lean"},
{img: "verbs/lick.svg", name:"to lick"},
{img: "verbs/lie.svg", name:"to lie"},
{img: "verbs/measure.svg", name:"to measure"},
{img: "verbs/point.svg", name:"to point"},
{img: "verbs/poke.svg", name:"to poke"},
{img: "verbs/pour.svg", name:"to pour"},
{img: "verbs/pray.svg", name:"to pray"},
{img: "verbs/press, squish.svg", name:"to press"},
{img: "verbs/pull.svg", name:"to pull"},
{img: "verbs/punch.svg", name:"to punch"},
{img: "verbs/push.svg", name:"to push"},
{img: "verbs/put.svg", name:"to put"},
{img: "verbs/read.svg", name:"to read"},
{img: "verbs/remove.svg", name:"to remove"},
{img: "verbs/ride.svg", name:"to ride"},
{img: "verbs/rotate.svg", name:"to rotate"},
{img: "verbs/run.svg", name:"to run"},
{img: "verbs/search.svg", name:"to search"},
{img: "verbs/share.svg", name:"to share"},
{img: "verbs/sit.svg", name:"to sit"},
{img: "verbs/sleep.svg", name:"to sleep"},
{img: "verbs/slip, slide.svg", name:"to slip"},
{img: "verbs/smoke.svg", name:"to smoke"},
{img: "verbs/sneeze.svg", name:"to sneeze"},
{img: "verbs/spit.svg", name:"to spit"},
{img: "verbs/squat.svg", name:"to squat"},
{img: "verbs/stand.svg", name:"to stand"},
{img: "verbs/start.svg", name:"to start"},
{img: "verbs/stop.svg", name:"to stop"},
{img: "verbs/stretch, pull.svg", name:"to stretch"},
{img: "verbs/strike, attack.svg", name:"to strike"},
{img: "verbs/suck.svg", name:"to suck"},
{img: "verbs/swim.svg", name:"to swim"},
{img: "verbs/take, pick.svg", name:"to take"},
{img: "verbs/tear-apart.svg", name:"to tear (apart)"},
{img: "verbs/throw, cast.svg", name:"to throw"},
{img: "verbs/touch.svg", name:"to touch"},
{img: "verbs/trade.svg", name:"to trade"},
{img: "verbs/turn.svg", name:"to turn"},
{img: "verbs/use.svg", name:"to use"},
{img: "verbs/vomit.svg", name:"to vomit"},
{img: "verbs/wait.svg", name:"to wait"},
{img: "verbs/walk, go.svg", name:"to walk"},
{img: "verbs/write.svg", name:"to write"},
// derivation
{img: "derivations/active.svg", name:"active"},
{img: "derivations/adverb, derivate.svg", name:"adverb"},
{img: "derivations/causative.svg", name:"causative"},
{img: "derivations/derivation, measure.svg", name:"measure, value (derivation)"},
{img: "derivations/more.svg", name:"more, -er"},
{img: "derivations/most.svg", name:"most, -est"},
{img: "derivations/passive.svg", name:"passive"},
{img: "derivations/rich (derivation).svg", name:"rich (derivation), -ous"},
{img: "derivations/worthy (derivation).svg", name:"worthy (derivation)"},
// misc
{img: "misc/AND.svg", name:"AND"},
{img: "misc/BUT.svg", name:"BUT"},
{img: "misc/FUT.svg", name:"Future tense suffix", half: true},
{img: "misc/INF.svg", name:"Infinitive suffix", half: true},
{img: "misc/OR.svg", name:"OR"},
{img: "misc/PLURAL.svg", name:"Plural suffix", half: true},
{img: "misc/PRES.svg", name:"Present tense suffix", half: true},
{img: "misc/PST.svg", name:"Past tense suffix", half: true},
// pronouns
{img: "pronoun/all.svg", name:"all"},
{img: "pronoun/any, multiplication.svg", name:"any, (number suffix)"},
{img: "pronoun/each-other.svg", name:"each-other"},
{img: "pronoun/every.svg", name:"every"},
{img: "pronoun/how.svg", name:"how"},
{img: "pronoun/if.svg", name:"if"},
{img: "pronoun/me.svg", name:"me"},
{img: "pronoun/necessary.svg", name:"necessary"},
{img: "pronoun/no.svg", name:"no"},
{img: "pronoun/possibly.svg", name:"possibly"},
{img: "pronoun/self.svg", name:"self"},
{img: "pronoun/some.svg", name:"some"},
{img: "pronoun/that.svg", name:"that"},
{img: "pronoun/this.svg", name:"this"},
{img: "pronoun/we.svg", name:"we"},
{img: "pronoun/what.svg", name:"what"},
{img: "pronoun/when.svg", name:"when"},
{img: "pronoun/where.svg", name:"where"},
{img: "pronoun/who.svg", name:"who"},
{img: "pronoun/you, thou.svg", name:"you"},
{img: "pronoun/you, yall.svg", name:"you"},
];